import 'articulos.dart';

class Lista {
  static List<Articulos> articulos = [
    Articulos(
      operador: "Centro de Apuestas",
      numero: "",
      urlimage: "/dist/animals_img/Oso_3.png",
      nombre: "Zapata",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "12",
      urlimage: "/dist/animals_img/Aguila_20.png",
      nombre: "Zapata",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "/dist/animals_img/Gato_16-min.webp",
      urlimage: "",
      nombre: "Zapata",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "12",
      urlimage: "/dist/animals_img/Carnero_14-min.webp",
      nombre: "Zapata",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "",
      urlimage: "/dist/animals_img/Carnero_14-min.webp",
      nombre: "Zapata",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "12",
      urlimage: "/dist/animals_img/Ballena_15.jpg",
      nombre: "Zapata",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "",
      urlimage: "/dist/animals_img/Leon_3.png",
      nombre: "Zapata",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "12",
      urlimage: "/dist/animals_img/Zamuro_19-min.png",
      nombre: "Zapata",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "",
      urlimage: "/dist/animals_img/Camello_2.png",
      nombre: "Zapata",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "12",
      urlimage: "/dist/animals_img/Ciempies_3.png",
      nombre: "Zapata",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "",
      urlimage: "/dist/animals_img/Lapa_15.jpg",
      nombre: "Zapata",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Centro de Apuestas",
      numero: "12",
      urlimage: "/dist/animals_img/Pavo_13-min.webp",
      nombre: "Zapata",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
  ];
}
